spring.application.name=Easypay
#DB Settings
spring.datasource.url=jdbc:mysql://localhost:3306/easy_pay_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Smit@001

#Hibernate Settings
spring.jpa.hibernate.ddl-auto = update